package org.npp.model.place.geojson;
  
import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonValue;
import org.npp.model.place.geojson.enums.GeoJsonGeometryTypeEnum;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.*;
import jakarta.annotation.Generated;

/**
 * GeoJson geometry object
 */

@Schema(name = "GeoJsonGeometry", description = "GeoJson geometry object")
@JsonIgnoreProperties(
  value = "geoJsonGeometryType", // ignore manually set geoJsonGeometryType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the geoJsonGeometryType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "geoJsonGeometryType", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = GeoJsonLineString.class, name = "GeoJsonLineString"),
  @JsonSubTypes.Type(value = GeoJsonMultiPolygon.class, name = "GeoJsonMultiPolygon"),
  @JsonSubTypes.Type(value = GeoJsonPoint.class, name = "GeoJsonPoint")
})


public class GeoJsonGeometry {

  /**
   * The GeoJson object type
   */
  public enum GeoJsonGeometryTypeEnum {
    GEOJSONPOINT("GeoJsonPoint"),
    
    GEOJSONLINESTRING("GeoJsonLineString"),
    
    GEOJSONMULTIPOLYGON("GeoJsonMultiPolygon");

    private String value;

    GeoJsonGeometryTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static GeoJsonGeometryTypeEnum fromValue(String value) {
      for (GeoJsonGeometryTypeEnum b : GeoJsonGeometryTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  private GeoJsonGeometryTypeEnum geoJsonGeometryType;

  private GeoJsonGeometryTypeEnum type;

  public GeoJsonGeometry() {
    super();
  }

  /**
   * Constructor with only required parameters
   */
  public GeoJsonGeometry(GeoJsonGeometryTypeEnum geoJsonGeometryType, GeoJsonGeometryTypeEnum type) {
    this.geoJsonGeometryType = geoJsonGeometryType;
    this.type = type;
  }

  public GeoJsonGeometry geoJsonGeometryType(GeoJsonGeometryTypeEnum geoJsonGeometryType) {
    this.geoJsonGeometryType = geoJsonGeometryType;
    return this;
  }

  /**
   * The GeoJson object type
   * @return geoJsonGeometryType
  */
  @NotNull 
  @Schema(name = "geoJsonGeometryType", description = "The GeoJson object type", requiredMode = Schema.RequiredMode.REQUIRED)
  @JsonProperty("geoJsonGeometryType")
  public GeoJsonGeometryTypeEnum getGeoJsonGeometryType() {
    return geoJsonGeometryType;
  }

  public void setGeoJsonGeometryType(GeoJsonGeometryTypeEnum geoJsonGeometryType) {
    this.geoJsonGeometryType = geoJsonGeometryType;
  }

  public GeoJsonGeometry type(GeoJsonGeometryTypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
  */
  @NotNull @Valid 
  @Schema(name = "type", requiredMode = Schema.RequiredMode.REQUIRED)
  @JsonProperty("type")
  public GeoJsonGeometryTypeEnum getType() {
    return type;
  }

  public void setType(GeoJsonGeometryTypeEnum type) {
    this.type = type;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeoJsonGeometry geoJsonGeometry = (GeoJsonGeometry) o;
    return Objects.equals(this.geoJsonGeometryType, geoJsonGeometry.geoJsonGeometryType) &&
        Objects.equals(this.type, geoJsonGeometry.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(geoJsonGeometryType, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeoJsonGeometry {\n");
    sb.append("    geoJsonGeometryType: ").append(toIndentedString(geoJsonGeometryType)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

